import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Header />
        <Footer/> */}
        {children}
      </body>
    </html>
  );
}

// export function Header() {
//   return (
//     <div>
//       <ul>
//         <li><Link href="/">Home</Link></li>
//         <li><Link href="/about">About</Link></li>
//         <li><Link href="/contact-us">Contact Us</Link></li>
//         <li><Link href="/career">Career</Link></li>
//       </ul>
//     </div>
//   );
// } 
//  export  function Footer (){
//   return(
//     <div>
//       <ul>
//         <li><Link href="www.youtube.com">Youtube</Link></li>
//         <li><Link href="www.google.com">Google</Link></li>
//       </ul>
//     </div>
//   )
// }